steps:
  # Build Container 2 image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'northamerica-northeast1-docker.pkg.dev/csci5409-428822/csci5409k8app1/k8img1', './Container1']

  # Push Container 1 image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'northamerica-northeast1-docker.pkg.dev/csci5409-428822/csci5409k8app1/k8img1']
  
  # Build Container 2 image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'northamerica-northeast1-docker.pkg.dev/csci5409-428822/csci5409k8app2/k8img2', './Container2']
  
  # Push Container 2 image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'northamerica-northeast1-docker.pkg.dev/csci5409-428822/csci5409k8app2/k8img2']

    # Fetch Kubernetes cluster credentials
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - 'csci5409-k8-assignment-cluster'
      - '--region=us-east1-c'
    env:
      - 'CLOUDSDK_CONTAINER_CLUSTER=csci5409-k8-assignment-cluster'
      - 'CLOUDSDK_COMPUTE_REGION=us-east1-c'

  # Deploy pv and pvc to Kubernetes cluster
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'deployment.yaml'
    env:
      - 'CLOUDSDK_CONTAINER_CLUSTER=csci5409-k8-assignment-cluster'
      - 'CLOUDSDK_COMPUTE_REGION=us-east1-c'

  # Deploy container 1 and corresponding service
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - './Container1/container1-deployment.yaml' 
    env:
      - 'CLOUDSDK_CONTAINER_CLUSTER=csci5409-k8-assignment-cluster'
      - 'CLOUDSDK_COMPUTE_REGION=us-east1-c'
    
    # Deploy container 2 and corresponding service
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - './Container2/container2-deployment.yaml' 
    env:
      - 'CLOUDSDK_CONTAINER_CLUSTER=csci5409-k8-assignment-cluster'
      - 'CLOUDSDK_COMPUTE_REGION=us-east1-c'


options:
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET