steps:
  # Build Container 2 image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'northamerica-northeast1-docker.pkg.dev/csci5409-428822/csci5409k8app1/k8img1:$SHORT_SHA', './Container1']
    env:
      - 'SHORT_SHA=$SHORT_SHA'
  
  # Push Container 1 image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'northamerica-northeast1-docker.pkg.dev/csci5409-428822/csci5409k8app1/k8img1:$SHORT_SHA']
  
  # Build Container 2 image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'northamerica-northeast1-docker.pkg.dev/csci5409-428822/csci5409k8app2/k8img2:$SHORT_SHA', './Container2']
    env:
      - 'SHORT_SHA=$SHORT_SHA'  # Export commit hash as environment variable
  
  # Push Container 2 image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'northamerica-northeast1-docker.pkg.dev/csci5409-428822/csci5409k8app2/k8img2:$SHORT_SHA']

    # Fetch Kubernetes cluster credentials
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - 'csci5409-k8-assignment-cluster'
      - '--region=us-central1'
    env:
      - 'CLOUDSDK_CONTAINER_CLUSTER=csci5409-k8-assignment-cluster'
      - 'CLOUDSDK_COMPUTE_REGION=us-central1'

  # Deploy to Kubernetes cluster
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'deployment.yaml'
    env:
      - 'CLOUDSDK_CONTAINER_CLUSTER=csci5409-k8-assignment-cluster'
      - 'CLOUDSDK_COMPUTE_REGION=us-central1'
options:
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET
