substitutions:
  _REGION: "us-east1-c"
  _IMAGE1_NAME: "northamerica-northeast1-docker.pkg.dev/csci5409-428822/csci5409k8app1/k8img1"
  _IMAGE2_NAME: "northamerica-northeast1-docker.pkg.dev/csci5409-428822/csci5409k8app2/k8img2"
  _GKE_CLUSTER_NAME: "csci5409-k8-assignment-cluster"

steps:
  # Build Container 1 image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '$_IMAGE1_NAME', './Container1']

  # Push Container 1 image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$_IMAGE1_NAME']
  
  # Build Container 2 image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '$_IMAGE2_NAME', './Container2']
  
  # Push Container 2 image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$_IMAGE2_NAME']

  # Fetch Kubernetes cluster credentials
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - '$_GKE_CLUSTER_NAME'
      - '--region=$_REGION'
    env:
      - 'CLOUDSDK_CONTAINER_CLUSTER=$_GKE_CLUSTER_NAME'
      - 'CLOUDSDK_COMPUTE_REGION=$_REGION'

  # Deploy pv and pvc to Kubernetes cluster
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'deployment.yaml'
    env:
      - 'CLOUDSDK_CONTAINER_CLUSTER=$_GKE_CLUSTER_NAME'
      - 'CLOUDSDK_COMPUTE_REGION=$_REGION'

  # Deploy container 1 and corresponding service
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - './Container1/container1-deployment.yaml' 
    env:
      - 'CLOUDSDK_CONTAINER_CLUSTER=$_GKE_CLUSTER_NAME'
      - 'CLOUDSDK_COMPUTE_REGION=$_REGION'
  
  # Deploy container 2 and corresponding service
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - './Container2/container2-deployment.yaml' 
    env:
      - 'CLOUDSDK_CONTAINER_CLUSTER=$_GKE_CLUSTER_NAME'
      - 'CLOUDSDK_COMPUTE_REGION=$_REGION'

options:
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET
