#Persistent volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: app1-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: gke-csci5409-k8-assignme-default-pool-081be150-wdp6
    fsType: ext4
---
#Claim the pesistent volume 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
