apiVersion: v1
kind: PersistentVolume
metadata:
  name: app1-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: gke-csci5409-k8-assignme-default-pool-081be150-wdp6
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app1-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: northamerica-northeast1-docker.pkg.dev/csci5409-428822/csci5409k8app1/k8img1:${SHORT_SHA}
        ports:
        - containerPort: 6000
        volumeMounts:
        - mountPath: /usr/src/app/data
          name: storage
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: app1-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: app2
        image: northamerica-northeast1-docker.pkg.dev/csci5409-428822/csci5409k8app2/k8img2:${SHORT_SHA}
        ports:
        - containerPort: 7200
        volumeMounts:
        - mountPath: /usr/src/app/data
          name: storage
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: app1-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: app1
spec:
  selector:
    app: app1
  ports:
  - protocol: TCP
    port: 6000
    targetPort: 6000
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: app2
spec:
  selector:
    app: app2
  ports:
  - protocol: TCP
    port: 7200
    targetPort: 7200
