#Deploy container 1 image from artifact registry in a pod
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: northamerica-northeast1-docker.pkg.dev/csci5409-428822/csci5409k8app1/k8img1:latest
        ports:
        - containerPort: 6000
        volumeMounts:                                       #Mount the claimed persistent volume as a volume
        - mountPath: /usr/src/app/data
          name: persistent-vol
      volumes:
      - name: persistent-vol
        persistentVolumeClaim:
          claimName: app-pvc
---
#Attach a node balancer service to pod, specify port forwarding
apiVersion: v1
kind: Service
metadata:
  name: app1
spec:
  selector:
    app: app1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 6000
  type: LoadBalancer